/**
	Generated by sails-inverse-model
	Date:Thu Mar 23 2017 12:42:42 GMT+0800 (China Standard Time)
*/

module.exports = {
  attributes: {
      case_no: {
          type: 'integer',
          notNull: true
      },
      category: {
          type: 'string',
          notNull: true
      },
      party: {
          type: 'string',
          notNull: true
      },
      id: {
          type: 'integer',
          unique: true,
          primaryKey: true,
          autoIncrement: true
      },
      createdAt: {
          type: 'datetime',
          notNull: true
      },
      updatedAt: {
          type: 'datetime',
          notNull: true
      },
  },
  tableName: 'cases'
};